# Generated by Django 4.2.6 on 2023-10-29 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('data_type_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FlaggedData',
            fields=[
                ('flagged_data_id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('data_value', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField()),
                ('data_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.datatype')),
            ],
        ),
    ]
