# Generated by Django 4.2.6 on 2023-10-31 12:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_flaggeddata_data_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flaggeddata',
            old_name='data_value',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='datatype',
            name='data_type_id',
        ),
        migrations.RemoveField(
            model_name='flaggeddata',
            name='flagged_data_id',
        ),
        migrations.AddField(
            model_name='datatype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='flaggeddata',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='flaggeddata',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
