# Generated by Django 4.2.6 on 2023-10-31 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_data_value_flaggeddata_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flaggeddata',
            old_name='data_type_id',
            new_name='data_type',
        ),
    ]
